export const ACTION_TYPE_ADD_TODO = 'ACTION_TYPE_ADD_TODO';
export const ACTION_TYPE_EDIT_TODO = 'ACTION_TYPE_EDIT_TODO';
export const ACTION_TYPE_DELETE_TODO = 'ACTION_TYPE_DELETE_TODO';
export const ACTION_TYPE_COMPLETE_TODO = 'ACTION_TYPE_COMPLETE_TODO';
export const ACTION_TYPE_CLEAR_TODO = 'ACTION_TYPE_CLEAR_TODO';

export const ACTION_TYPE_RESIZE_SIDE_PANEL = 'ACTION_TYPE_RESIZE_SIDE_PANEL';