export const ACTION_TYPE_ADD_TODO = 0x01;
export const ACTION_TYPE_EDIT_TODO = 0x02;
export const ACTION_TYPE_DELETE_TODO = 0x03;
export const ACTION_TYPE_COMPLETE_TODO = 0x04;
export const ACTION_TYPE_CLEAR_TODO = 0x05;